import type { Workflow } from "./types";

export const sampleWorkflow: Workflow = {
  id: "W1",
  name: "Workflow ที่ 1 การต้อนรับอาคันตุกะต่างชาติ",
  sourceFile: "gold_standard_workflow_1.pdf",
  sourceText: `Workflow ที่ 1 การต้อนรับอาคันตุกะต่างชาติ
หน่วยงานภายนอกคณะ: สถาบันต่างประเทศแจ้งความประสงค์การเข้าพบและวันเวลาสะดวก
หน่วยงานภายในคณะ: สารบรรณ, กองกิจการนิสิต/นิสิต, ภาควิชา/โครงการ, แจ้งฝ่ายอาคารและสถานที่, แจ้งฝ่ายโสตฯ, งานคลังและพัสดุ
ศูนย์วิเทศสัมพันธ์ฯ และ หัวหน้าศูนย์นวัตกรรม: เจ้าหน้าที่บริหารงานทั่วไป, หัวหน้าศูนย์วิเทศสัมพันธ์, หัวหน้าศูนย์นวัตกรรม, จัดทำหนังสือและรายละเอียดการเยือนฯ, จัดเตรียมเอกสาร, จัดเตรียมกิจกรรม, จัดเตรียมเอกสารเบิกจ่าย, FINAL
ผู้บริหารที่เกี่ยวข้อง: หัวหน้าสำนักงานเลขานุการ, รองคณบดีฝ่ายวิเทศฯ, คณบดี พินิจพิจารณา`,
  lanes: [
    "หน่วยงานภายนอกคณะ",
    "หน่วยงานภายในคณะ",
    "ศูนย์วิเทศสัมพันธ์ฯ และ หัวหน้าศูนย์นวัตกรรม",
    "ผู้บริหารที่เกี่ยวข้อง"
  ],
  nodes: [
    {
      id: "W1-N01",
      text: "สถาบันต่างประเทศแจ้งความประสงค์การเข้าพบและวันเวลาสะดวก",
      originalText: "สถาบันต่างประเทศแจ้งความประสงค์การเข้าพบและวันเวลาสะดวก",
      lane: "หน่วยงานภายนอกคณะ",
      type: "start",
      documents: "หนังสือแจ้งความประสงค์",
      sourceRef: "ข้อความลำดับที่ 1",
      confidence: "high",
      order: 1
    },
    {
      id: "W1-N02",
      text: "Option 1: ประสานทางเลือก 1",
      originalText: "Option 1",
      lane: "หน่วยงานภายนอกคณะ",
      type: "option",
      documents: "",
      sourceRef: "ทางเลือก 1",
      confidence: "high",
      order: 2
    },
    {
      id: "W1-N03",
      text: "Option 2: ประสานทางเลือก 2",
      originalText: "Option 2",
      lane: "หน่วยงานภายนอกคณะ",
      type: "option",
      documents: "",
      sourceRef: "ทางเลือก 2",
      confidence: "high",
      order: 3
    },
    {
      id: "W1-N04",
      text: "Option 3: ประสานทางเลือก 3",
      originalText: "Option 3",
      lane: "หน่วยงานภายนอกคณะ",
      type: "option",
      documents: "",
      sourceRef: "ทางเลือก 3",
      confidence: "high",
      order: 4
    },
    {
      id: "W1-N05",
      text: "Option 4: ประสานทางเลือก 4",
      originalText: "Option 4",
      lane: "หน่วยงานภายนอกคณะ",
      type: "option",
      documents: "",
      sourceRef: "ทางเลือก 4",
      confidence: "high",
      order: 5
    },
    {
      id: "W1-N06",
      text: "สารบรรณ",
      originalText: "สารบรรณ",
      lane: "หน่วยงานภายในคณะ",
      type: "process",
      documents: "",
      sourceRef: "ข้อความลำดับที่ 2",
      confidence: "high",
      order: 6
    },
    {
      id: "W1-N07",
      text: "ภาควิชา / โครงการ",
      originalText: "ภาควิชา / โครงการ",
      lane: "หน่วยงานภายในคณะ",
      type: "process",
      documents: "",
      sourceRef: "ข้อความลำดับที่ 3",
      confidence: "high",
      order: 7
    },
    {
      id: "W1-N08",
      text: "เจ้าหน้าที่บริหารงานทั่วไป รับเรื่อง เสนอประมาณการ",
      originalText: "เจ้าหน้าที่บริหารงานทั่วไป รับเรื่อง เสนอประมาณการ",
      lane: "ศูนย์วิเทศสัมพันธ์ฯ และ หัวหน้าศูนย์นวัตกรรม",
      type: "process",
      documents: "",
      sourceRef: "ข้อความลำดับที่ 4",
      confidence: "high",
      order: 8
    },
    {
      id: "W1-N09",
      text: "หัวหน้าศูนย์วิเทศสัมพันธ์",
      originalText: "หัวหน้าศูนย์วิเทศสัมพันธ์",
      lane: "ศูนย์วิเทศสัมพันธ์ฯ และ หัวหน้าศูนย์นวัตกรรม",
      type: "process",
      documents: "",
      sourceRef: "ข้อความลำดับที่ 5",
      confidence: "high",
      order: 9
    },
    {
      id: "W1-N10",
      text: "หัวหน้าศูนย์นวัตกรรม",
      originalText: "หัวหน้าศูนย์นวัตกรรม",
      lane: "ศูนย์วิเทศสัมพันธ์ฯ และ หัวหน้าศูนย์นวัตกรรม",
      type: "process",
      documents: "",
      sourceRef: "ข้อความลำดับที่ 6",
      confidence: "high",
      order: 10
    },
    {
      id: "W1-N11",
      text: "หัวหน้าสำนักงานเลขานุการ",
      originalText: "หัวหน้าสำนักงานเลขานุการ",
      lane: "ผู้บริหารที่เกี่ยวข้อง",
      type: "executive",
      documents: "",
      sourceRef: "ข้อความลำดับที่ 7",
      confidence: "high",
      order: 11
    },
    {
      id: "W1-N12",
      text: "รองคณบดี ฝ่ายวิเทศฯ",
      originalText: "รองคณบดี ฝ่ายวิเทศฯ",
      lane: "ผู้บริหารที่เกี่ยวข้อง",
      type: "executive",
      documents: "",
      sourceRef: "ข้อความลำดับที่ 8",
      confidence: "high",
      order: 12
    },
    {
      id: "W1-N13",
      text: "คณบดี พิจารณา",
      originalText: "คณบดี พิจารณา",
      lane: "ผู้บริหารที่เกี่ยวข้อง",
      type: "executive",
      documents: "",
      sourceRef: "ข้อความลำดับที่ 9",
      confidence: "high",
      order: 13
    },
    {
      id: "W1-N14",
      text: "จัดทำหนังสือและรายละเอียดการเยือนการหาใน\n• การแลกเปลี่ยนนิสิตระดับปริญญาตรี/โท/เอก\n• การทำ double degree / dual degree\n• การทำวิจัยร่วมกัน\n• โครงการเยือน การจัดเรียงสถานที่\n• ฝ่ายต้องได้รายชื่อผู้เข้าร่วม\n• ขอทราบหลักสูตรแผนงานในประเทศ\n• ของที่ระลึก (นำมาจากสำนักงานเลขานุการ)\n• คำกล่าว, เล่มกล่าว\n• วีดิทัศน์แนะนำคณะ",
      originalText: "จัดทำหนังสือและรายละเอียดการเยือนการหาใน...",
      lane: "ศูนย์วิเทศสัมพันธ์ฯ และ หัวหน้าศูนย์นวัตกรรม",
      type: "document",
      documents: "หนังสือและรายละเอียดการเยือนฯ",
      sourceRef: "ข้อความลำดับที่ 10",
      confidence: "high",
      order: 14
    },
    {
      id: "W1-N15",
      text: "แจ้งฝ่ายอาคารและสถานที่\n• กรณีห้องส่งเสด็จ\n• กรณีต้อนรับอาคันตุกะต่างชาติ",
      originalText: "แจ้งฝ่ายอาคารและสถานที่",
      lane: "หน่วยงานภายในคณะ",
      type: "process",
      documents: "",
      sourceRef: "ข้อความลำดับที่ 11",
      confidence: "high",
      order: 15
    },
    {
      id: "W1-N16",
      text: "แจ้งฝ่ายโสตฯ\n• จัดทำลิงก์ออนไลน์\n• อุปกรณ์อนุมัติสำหรับการประชุมหรือจัดงาน",
      originalText: "แจ้งฝ่ายโสตฯ",
      lane: "หน่วยงานภายในคณะ",
      type: "process",
      documents: "",
      sourceRef: "ข้อความลำดับที่ 12",
      confidence: "high",
      order: 16
    },
    {
      id: "W1-N17",
      text: "จัดเตรียมเอกสาร\n• แบบเสนอโครงการ\n• บันทึกขออนุมัติจัดจ่าย\n• สำเนางบประมาณ\n• สำเนาหนังสือ 2 ฉบับ",
      originalText: "จัดเตรียมเอกสาร",
      lane: "ศูนย์วิเทศสัมพันธ์ฯ และ หัวหน้าศูนย์นวัตกรรม",
      type: "document",
      documents: "แบบเสนอโครงการ, บันทึกขออนุมัติจัดจ่าย, สำเนางบประมาณ",
      sourceRef: "ข้อความลำดับที่ 13",
      confidence: "high",
      order: 17
    },
    {
      id: "W1-N18",
      text: "เจ้าหน้าที่บริหารงานทั่วไป รับเรื่อง เสนอพิจารณา",
      originalText: "เจ้าหน้าที่บริหารงานทั่วไป รับเรื่อง เสนอพิจารณา",
      lane: "ศูนย์วิเทศสัมพันธ์ฯ และ หัวหน้าศูนย์นวัตกรรม",
      type: "process",
      documents: "",
      sourceRef: "ข้อความลำดับที่ 14",
      confidence: "high",
      order: 18
    },
    {
      id: "W1-N19",
      text: "หัวหน้าศูนย์วิเทศสัมพันธ์",
      originalText: "หัวหน้าศูนย์วิเทศสัมพันธ์",
      lane: "ศูนย์วิเทศสัมพันธ์ฯ และ หัวหน้าศูนย์นวัตกรรม",
      type: "process",
      documents: "",
      sourceRef: "ข้อความลำดับที่ 15",
      confidence: "high",
      order: 19
    },
    {
      id: "W1-N20",
      text: "หัวหน้าศูนย์นวัตกรรม",
      originalText: "หัวหน้าศูนย์นวัตกรรม",
      lane: "ศูนย์วิเทศสัมพันธ์ฯ และ หัวหน้าศูนย์นวัตกรรม",
      type: "process",
      documents: "",
      sourceRef: "ข้อความลำดับที่ 16",
      confidence: "high",
      order: 20
    },
    {
      id: "W1-N21",
      text: "หัวหน้าสำนักงานเลขา",
      originalText: "หัวหน้าสำนักงานเลขา",
      lane: "ผู้บริหารที่เกี่ยวข้อง",
      type: "executive",
      documents: "",
      sourceRef: "ข้อความลำดับที่ 17",
      confidence: "high",
      order: 21
    },
    {
      id: "W1-N22",
      text: "รองคณบดี ฝ่ายวิเทศฯ",
      originalText: "รองคณบดี ฝ่ายวิเทศฯ",
      lane: "ผู้บริหารที่เกี่ยวข้อง",
      type: "executive",
      documents: "",
      sourceRef: "ข้อความลำดับที่ 18",
      confidence: "high",
      order: 22
    },
    {
      id: "W1-N23",
      text: "คณบดี พิจารณา",
      originalText: "คณบดี พิจารณา",
      lane: "ผู้บริหารที่เกี่ยวข้อง",
      type: "executive",
      documents: "",
      sourceRef: "ข้อความลำดับที่ 19",
      confidence: "high",
      order: 23
    },
    {
      id: "W1-N24",
      text: "งานคลังและพัสดุ (ขออนุมัติค่าใช้จ่าย)",
      originalText: "งานคลังและพัสดุ",
      lane: "หน่วยงานภายในคณะ",
      type: "process",
      documents: "",
      sourceRef: "ข้อความลำดับที่ 20",
      confidence: "high",
      order: 24
    },
    {
      id: "W1-N25",
      text: "เจ้าหน้าที่บริหารงานทั่วไป",
      originalText: "เจ้าหน้าที่บริหารงานทั่วไป",
      lane: "ศูนย์วิเทศสัมพันธ์ฯ และ หัวหน้าศูนย์นวัตกรรม",
      type: "process",
      documents: "",
      sourceRef: "ข้อความลำดับที่ 21",
      confidence: "high",
      order: 25
    },
    {
      id: "W1-N26",
      text: "จัดเตรียมกิจกรรม\n• เตรียมขอคารวะ/อาหาร\n• เริ่มดำเนินกิจกรรม\n• คณบดีกล่าวต้อนรับ\n• เปิดวีดิทัศน์แนะนำคณะ\n• หารือความร่วมมือ\n• ถ่ายรูปมอบของระลึก\n• แจ้งฝ่ายอาคารและสถานที่การใช้อุปกรณ์\n• ผู้ช่วยคณบดีประจำต้อนรับ\n• รายงานโครงการ ให้ฝ่ายสารบรรณทำการหารือกับวิทยากรผ่านคณะ",
      originalText: "จัดเตรียมกิจกรรม",
      lane: "ศูนย์วิเทศสัมพันธ์ฯ และ หัวหน้าศูนย์นวัตกรรม",
      type: "process",
      documents: "",
      sourceRef: "ข้อความลำดับที่ 22",
      confidence: "high",
      order: 26
    },
    {
      id: "W1-N27",
      text: "จัดเตรียมเอกสารเบิกจ่าย\n• เบิกจ่ายเงิน 20,000 บาท\n• บันทึกเบิกจ่ายใน-ในเรือ\n• ใบเสร็จรับเงิน/ใบเสร็จรับเงิน\n• แบบ กค 2001\n• แบบฟอร์มรับเงิน (ถ้ามี)\n• โครงการได้รับอนุมัติ\n• ใบเสนอราคา",
      originalText: "จัดเตรียมเอกสารเบิกจ่าย",
      lane: "ศูนย์วิเทศสัมพันธ์ฯ และ หัวหน้าศูนย์นวัตกรรม",
      type: "document",
      documents: "ใบเสร็จรับเงิน, แบบ กค 2001, ใบเสนอราคา",
      sourceRef: "ข้อความลำดับที่ 23",
      confidence: "high",
      order: 27
    },
    {
      id: "W1-N28",
      text: "รองคณบดี ฝ่ายวิเทศฯ ลงนาม",
      originalText: "รองคณบดี ฝ่ายวิเทศฯ ลงนาม",
      lane: "ผู้บริหารที่เกี่ยวข้อง",
      type: "executive",
      documents: "",
      sourceRef: "ข้อความลำดับที่ 24",
      confidence: "high",
      order: 28
    },
    {
      id: "W1-N29",
      text: "งานคลังและพัสดุ",
      originalText: "งานคลังและพัสดุ",
      lane: "หน่วยงานภายในคณะ",
      type: "process",
      documents: "",
      sourceRef: "ข้อความลำดับที่ 25",
      confidence: "high",
      order: 29
    },
    {
      id: "W1-N30",
      text: "สารบรรณ",
      originalText: "สารบรรณ",
      lane: "หน่วยงานภายในคณะ",
      type: "process",
      documents: "",
      sourceRef: "ข้อความลำดับที่ 26",
      confidence: "high",
      order: 30
    },
    {
      id: "W1-N31",
      text: "FINAL เสร็จสิ้น",
      originalText: "FINAL เสร็จสิ้น",
      lane: "ศูนย์วิเทศสัมพันธ์ฯ และ หัวหน้าศูนย์นวัตกรรม",
      type: "end",
      documents: "",
      sourceRef: "ข้อความลำดับที่ 27",
      confidence: "high",
      order: 31
    }
  ],
  edges: [
    { id: "W1-E01", source: "W1-N01", target: "W1-N02", label: "Option 1", color: "#16A34A", style: "solid", sourceSide: "top", targetSide: "left" },
    { id: "W1-E02", source: "W1-N01", target: "W1-N03", label: "Option 2", color: "#EA580C", style: "solid", sourceSide: "top", targetSide: "left" },
    { id: "W1-E03", source: "W1-N01", target: "W1-N06", label: "Option 3", color: "#0284C7", style: "solid", sourceSide: "bottom", targetSide: "top" },
    { id: "W1-E04", source: "W1-N01", target: "W1-N07", label: "Option 4", color: "#7C3AED", style: "solid", sourceSide: "bottom", targetSide: "top" },
    { id: "W1-E05", source: "W1-N06", target: "W1-N08", label: "", color: "#000000", style: "solid", sourceSide: "right", targetSide: "left" },
    { id: "W1-E06", source: "W1-N07", target: "W1-N08", label: "", color: "#000000", style: "solid", sourceSide: "right", targetSide: "left" },
    { id: "W1-E07", source: "W1-N08", target: "W1-N09", label: "", color: "#000000", style: "solid", sourceSide: "bottom", targetSide: "top" },
    { id: "W1-E08", source: "W1-N09", target: "W1-N10", label: "", color: "#000000", style: "solid", sourceSide: "bottom", targetSide: "top" },
    { id: "W1-E09", source: "W1-N10", target: "W1-N11", label: "", color: "#000000", style: "solid", sourceSide: "right", targetSide: "left" },
    { id: "W1-E10", source: "W1-N11", target: "W1-N12", label: "", color: "#000000", style: "solid", sourceSide: "bottom", targetSide: "top" },
    { id: "W1-E11", source: "W1-N12", target: "W1-N13", label: "เสนอคณบดีอนุมัติ", color: "#16A34A", style: "solid", sourceSide: "top", targetSide: "bottom" },
    { id: "W1-E12", source: "W1-N13", target: "W1-N01", label: "ปฏิเสธการจัดกิจกรรม", color: "#DC2626", style: "solid", sourceSide: "top", targetSide: "top" },
    { id: "W1-E13", source: "W1-N12", target: "W1-N01", label: "ปฏิเสธการจัดกิจกรรม", color: "#DC2626", style: "solid", sourceSide: "top", targetSide: "top" },
    { id: "W1-E14", source: "W1-N13", target: "W1-N14", label: "เห็นชอบจัดกิจกรรม", color: "#16A34A", style: "solid", sourceSide: "bottom", targetSide: "right" },
    { id: "W1-E15", source: "W1-N14", target: "W1-N15", label: "", color: "#000000", style: "solid", sourceSide: "bottom", targetSide: "right" },
    { id: "W1-E16", source: "W1-N14", target: "W1-N16", label: "", color: "#000000", style: "solid", sourceSide: "bottom", targetSide: "right" },
    { id: "W1-E17", source: "W1-N14", target: "W1-N17", label: "", color: "#000000", style: "solid", sourceSide: "bottom", targetSide: "top" },
    { id: "W1-E18", source: "W1-N17", target: "W1-N18", label: "", color: "#000000", style: "solid", sourceSide: "bottom", targetSide: "top" },
    { id: "W1-E19", source: "W1-N18", target: "W1-N19", label: "", color: "#000000", style: "solid", sourceSide: "bottom", targetSide: "top" },
    { id: "W1-E20", source: "W1-N19", target: "W1-N20", label: "", color: "#000000", style: "solid", sourceSide: "bottom", targetSide: "top" },
    { id: "W1-E21", source: "W1-N20", target: "W1-N21", label: "", color: "#000000", style: "solid", sourceSide: "right", targetSide: "left" },
    { id: "W1-E22", source: "W1-N21", target: "W1-N22", label: "", color: "#000000", style: "solid", sourceSide: "top", targetSide: "bottom" },
    { id: "W1-E23", source: "W1-N22", target: "W1-N23", label: "อนุมัติโครงการ", color: "#DB2777", style: "dash", sourceSide: "top", targetSide: "bottom" },
    { id: "W1-E24", source: "W1-N23", target: "W1-N24", label: "ขออนุมัติค่าใช้จ่าย", color: "#DB2777", style: "dash", sourceSide: "bottom", targetSide: "right" },
    { id: "W1-E25", source: "W1-N24", target: "W1-N25", label: "อนุมัติค่าใช้จ่าย", color: "#DB2777", style: "dash", sourceSide: "right", targetSide: "left" },
    { id: "W1-E26", source: "W1-N25", target: "W1-N26", label: "ดำเนินการ", color: "#000000", style: "solid", sourceSide: "bottom", targetSide: "top" },
    { id: "W1-E27", source: "W1-N26", target: "W1-N27", label: "", color: "#000000", style: "solid", sourceSide: "bottom", targetSide: "top" },
    { id: "W1-E28", source: "W1-N27", target: "W1-N28", label: "", color: "#000000", style: "solid", sourceSide: "right", targetSide: "left" },
    { id: "W1-E29", source: "W1-N28", target: "W1-N29", label: "", color: "#DB2777", style: "dash", sourceSide: "left", targetSide: "right" },
    { id: "W1-E30", source: "W1-N29", target: "W1-N30", label: "", color: "#DB2777", style: "dash", sourceSide: "left", targetSide: "right" },
    { id: "W1-E31", source: "W1-N27", target: "W1-N31", label: "", color: "#000000", style: "solid", sourceSide: "bottom", targetSide: "top" }
  ],
  createdAt: new Date().toISOString(),
  analysisMode: "sample"
};
